$(document).ready(function(){
        /* 1st */
       $('#icon1_1').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_1.png");
           $("#icon1_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon1_3').attr("src","../common/images/quiz/icon_g_3.png");
       });
        $('#icon1_2').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_2.png");
           $("#icon1_1").attr("src","../common/images/quiz/icon_g_1.png");
           $('#icon1_3').attr("src","../common/images/quiz/icon_g_3.png");
       }); 
        $('#icon1_3').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_3.png");
           $("#icon1_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon1_1').attr("src","../common/images/quiz/icon_g_1.png");
       }); 
        /* 2nd */
        $('#icon2_1').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_1.png");
           $("#icon2_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon2_3').attr("src","../common/images/quiz/icon_g_3.png");
       });
        $('#icon2_2').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_2.png");
           $("#icon2_1").attr("src","../common/images/quiz/icon_g_1.png");
           $('#icon2_3').attr("src","../common/images/quiz/icon_g_3.png");
       }); 
        $('#icon2_3').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_3.png");
           $("#icon2_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon2_1').attr("src","../common/images/quiz/icon_g_1.png");
       }); 
        /* 3rd */
        $('#icon3_1').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_1.png");
           $("#icon3_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon3_3').attr("src","../common/images/quiz/icon_g_3.png");
       });
        $('#icon3_2').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_2.png");
           $("#icon3_1").attr("src","../common/images/quiz/icon_g_1.png");
           $('#icon3_3').attr("src","../common/images/quiz/icon_g_3.png");
       }); 
        $('#icon3_3').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_3.png");
           $("#icon3_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon3_1').attr("src","../common/images/quiz/icon_g_1.png");
       }); 
        /* 4th */
        $('#icon4_1').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_1.png");
           $("#icon4_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon4_3').attr("src","../common/images/quiz/icon_g_3.png");
       });
        $('#icon4_2').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_2.png");
           $("#icon4_1").attr("src","../common/images/quiz/icon_g_1.png");
           $('#icon4_3').attr("src","../common/images/quiz/icon_g_3.png");
       }); 
        $('#icon4_3').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_3.png");
           $("#icon4_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon4_1').attr("src","../common/images/quiz/icon_g_1.png");
       }); 
        /* 5th */
        $('#icon5_1').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_1.png");
           $("#icon5_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon5_3').attr("src","../common/images/quiz/icon_g_3.png");
       });
        $('#icon5_2').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_2.png");
           $("#icon5_1").attr("src","../common/images/quiz/icon_g_1.png");
           $('#icon5_3').attr("src","../common/images/quiz/icon_g_3.png");
       }); 
        $('#icon5_3').click(function(){
           $(this).attr("src","../common/images/quiz/icon_c_3.png");
           $("#icon5_2").attr("src","../common/images/quiz/icon_g_2.png");
           $('#icon5_1').attr("src","../common/images/quiz/icon_g_1.png");
       }); 
    });
        